### ISSUE TITLE
Options dont get saved in blocks

### ISSUE THREAD

**Issue by caplod** [sylvainjule/kirby-imageradio#12]
I have a blueprint where I extend the (new in kirby 3.5) block type gallery like so:

      projectgallery:
        label: Gallery
        type: blocks
        fieldsets:
          gallery:
            extends: blocks/gallery
            fields:
              images:
                max: 3
              display:
                label: Display
                type: imageradio
                columns: 4
                ratio: 3/2
                gap: true
                fit: contain
                options:
                  layout1:
                    text: Layout 1
                    image: layout1.svg
                  layout2:
                    text: Layout 2
                    image: layout2.svg

it looks fine in the backend:

<img width="777" alt="Bildschirmfoto 2021-02-08 um 09 04 29" src="https://user-images.githubusercontent.com/435070/107191603-aff1f480-69ec-11eb-913d-fc025e17f6a9.png">

but when I save, the display value doesnt get saved:
project.txt

    ----

    Projectgallery: [{"content":{"images":["image_1.jpg"]},"id":"0ef7bf26-a46d-4465-b4fa-424c7f9928f3","isHidden":false,"type":"gallery"}]

    ----

**Comment by gegerino** [comment]
Is there a solution right now?

**Comment by sylvainjule** [comment]
This is fixed in the latest release!
