### ISSUE TITLE
Kirby 4 compatibility

### ISSUE THREAD

**Issue by squareclouds** [sylvainjule/kirby-imageradio#18]
It would be great to have a K4 compatible version of this! :)

**Comment by bogdancondorachi** [comment]
Hello, @sylvainjule any news about a k4 port? I've seen that Kirby\Form\Options class was deprecated and a port would maybe require a rewrite under Kirby/Option/Options class.

**Comment by Afplaktape** [comment]
Would really appreciate a fix for Kirby 4 :)

**Comment by sylvainjule** [comment]
2.0.0 is compatible with K4 ✓
