### ISSUE TITLE
Using smaller thumbnails

### ISSUE THREAD

**Issue by schnti** [sylvainjule/kirby-imageradio#3]
Panel takes a long time to load with many large pictures. 
The kirby files view uses 400px thumbnails. Perhaps the plugin can use this too.

![screenshot 2017-09-28 08 51 04](https://user-images.githubusercontent.com/1868482/30953048-95f13996-a42a-11e7-95c2-b8829e739ba9.png)

**Comment by sylvainjule** [comment]
Yes, you're right. I added it in the last commit. ;)
