### ISSUE TITLE
text: option not work

### ISSUE THREAD

**Issue by pfrlv** [sylvainjule/kirby-imageradio#8]
Option like a `text: "Pic: {{ file.filename }} Size: {{ file.modified('d Y') }}"` — not work for me. I see only filename always 😕. Kirby 3.1.1

**Comment by sylvainjule** [comment]
Kirby will only render one brackets-string. I guess it's not specific to this plugin and would produce the same output in other core-fields?

You'd have to make it a file method:

```php
'fileMethods' => [
    'toInfos' => function() {
        return 'Pic: ' . $this->filename() . ' Size: '. $this->modified("d Y")';
    },
}
```

Then: 

```yaml
text: '{{ file.toInfos }}'
```

**Comment by sylvainjule** [comment]
Closing this issue since it'll most likely fix your problem. Please feel free to reopen if it doesn't.
